[package]
name = "moredata-scheduler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Realtime multithreaded scheduler for MoreData"
publish = false

[dependencies]
moredata-core.workspace = true
